In [15]:
import numpy as np

# ARRAYS

In [16]:
benimListem=[1,2,3,4,5]

In [17]:
np.array(benimListem)  # listeyi arraye çevirdik.

array([1, 2, 3, 4, 5])

In [18]:
matrixListesi=[[1,2,3],[4,5,6],[7,8,9]]


In [19]:
matrixListesi[1] # matrix listesinin 1. elemanını çağırdık

[4, 5, 6]

In [20]:
np.array(matrixListesi)  # numpy array dizisine çevirdik

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# ARANGE

In [21]:
np.arange(1,10)   # 1'den 10'a kadar sayı üretttik
        

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(1,20,2) # 1'den 20'ye kadar ikişer ikişer gidiyor

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])


# LİNSPACE

In [23]:
np.linspace(0,20,5)  # eşit olarak aralık bırakılmış dizi oluşturur

array([ 0.,  5., 10., 15., 20.])

# RANDOM

In [25]:
np.random.randn(8) # içine kaç tane değer döneceğini yazıyoruz ve rastgele array oluşturdu.

array([-0.21400892, -1.06170712,  1.4055088 , -1.80247937,  0.77559812,
        0.51538713, -1.8163408 ,  1.49481417])

In [26]:
np.random.randint(1,10) # 1 den 10 a kadar herhangi bir int değeri döndürür

6

In [28]:
np.random.randint(1,50,5) # 1 den 50 ye kadar 5 tane int sayı üretti

array([47, 31, 43, 16,  1])

In [31]:
benimNumpyDizim=np.arange(30) # np.arange 'i diziye eşitleme

In [32]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [35]:
benimRandomDizim=np.random.randint(0,100,20)

In [36]:
benimRandomDizim

array([41, 19, 56, 84, 84, 72, 88, 59, 98, 53, 66, 77, 82, 20, 21, 30, 56,
       28, 45, 49])

# NUMPY DİZİ METHODLARI

In [39]:
benimNumpyDizim.reshape(5,6)  # Dizimizi yeniden şekillendirip matrise çeviridk.

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [41]:
benimNumpyDizim.max()

29

In [42]:
benimRandomDizim.argmin() # 1. indekste en küçük değerin olduğunu söyler

1

In [43]:
reshapeDizim=benimNumpyDizim.reshape(5,6) # kullabilmek için bir değişkene atmamız gerekiyor

In [44]:
reshapeDizim

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [45]:
reshapeDizim.shape # kaça kaçlık matris olduğunu verir

(5, 6)