In [1]:
import numpy as np

In [2]:
benimDizim=np.arange(0,15)

In [3]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
benimDizim[5] # 5. indeksi alma

5

In [6]:
benimDizim[3:5] # 3 den 5 e kadar indeksler 

array([3, 4])

In [7]:
benimDizim[3:8]=-5 # 3 den 8 e kadar olan sayıları -5 ile değişti

In [8]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [9]:
baskaDizi=np.arange(0,24)

In [10]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [11]:
Dizi=baskaDizi[4:9] #4 den 9 a kadar olan elemanları dizi içerisine attık

In [12]:
Dizi[:]=700 # dizi içerisindeki tüm elemanları 700'e eşitledik.

In [13]:
Dizi

array([700, 700, 700, 700, 700])

In [14]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

# Matrix

In [15]:
benimListem=[[10,20,30],[40,50,60],[70,80,90]]

In [16]:
benimMatrixDizim=np.array(benimListem) # indekse çeviridk

In [17]:
benimMatrixDizim

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [18]:
benimMatrixDizim[0] # 0. indeksi getirdi

array([10, 20, 30])

In [19]:
benimMatrixDizim[1,2] # 1. indeksin 2.indeksini getir gibi

60

In [20]:
benimMatrixDizim[1:,2] # 1 den son indekse kadar olanlar 40,50,60,70,80,90
                       # bunların içinden yalnızca 2. indeksleri al

array([60, 90])

In [21]:
benimMatrixDizim[[1,2,0]] # 1.  2. ve 0. indeksleri getiridik.

array([[40, 50, 60],
       [70, 80, 90],
       [10, 20, 30]])

# Operasyonlar

In [26]:
yeniBirDizi=np.random.randint(1,100,20)

In [27]:
yeniBirDizi

array([19, 40, 28, 63, 26, 53, 88, 10, 76, 60,  6, 41, 73, 26, 65, 25, 28,
       32, 28, 17])

In [28]:
yeniBirDizi>24

array([False,  True,  True,  True,  True,  True,  True, False,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True, False])

In [29]:
sonuc=yeniBirDizi>24

In [30]:
sonuc

array([False,  True,  True,  True,  True,  True,  True, False,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True, False])

In [31]:
yeniBirDizi[sonuc] # rakamları filtreledik 

array([40, 28, 63, 26, 53, 88, 76, 60, 41, 73, 26, 65, 25, 28, 32, 28])

In [32]:
sonDizi=np.arange(0,24)

In [33]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [34]:
sonDizi+sonDizi  # iki tane sondiziyi topladı

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [35]:
np.sqrt(sonDizi) # son dizinin karekökünü aldık

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [36]:
np.max(sonDizi)  # max elemanı

23

In [38]:
np.min(sonDizi) # min elemanı

0