In [85]:
8%%5
8%/%5
8/4*2
sqrt(5)
exp(1)
log(100)

[1] 3

[1] 1

[1] 4

[1] 2.236068

[1] 2.718282

[1] 4.60517

In [12]:
log(100,10)

[1] 2

In [13]:
x<-8

In [14]:
x

[1] 8

In [17]:
a<-3; b<-4;c<- -1

In [18]:
x1<-(-b+sqrt(b**2-4*a*c))/(2*a)

In [19]:
x1

[1] 0.2152504

In [21]:
x2<-(-b-sqrt(b**2-4*a*c))/(2*a)

In [22]:
x2

[1] -1.548584

In [23]:
x<-5

In [24]:
typeof(x)

[1] "double"

In [25]:
x<-5L

In [26]:
typeof(x)

[1] "integer"

In [27]:
x1 > x2 & x1 > 0

[1] TRUE

In [29]:
x1 > x2 | x1 > 0

[1] TRUE

In [30]:
!(x1 > x2 | x1 > 0)

[1] FALSE

In [64]:
x<-runif(10,min=3,max=10)

In [65]:
x<-rnorm(10,mean=3,sd=1.2)

In [69]:
x<-rnorm(100)   # x'in -0,5 ile 0,5 arasında kalan değerlerini 0 yap

In [70]:
x[x>-0.5 & x < 0.5]

[1]  0.298912850  0.144857780  0.420580578 -0.460790427  0.183293752
 [6]  0.080841360  0.227456426  0.144196646 -0.134495207 -0.394574273
[11] -0.110926055  0.353909527 -0.018017238 -0.402651890 -0.203071295
[16]  0.421932934 -0.247356005 -0.423174031 -0.009592446  0.237279557
[21]  0.182220816 -0.235026740  0.414396780  0.164002700 -0.337540803
[26]  0.373564562  0.430063885  0.232158151 -0.190270163 -0.443248834
[31] -0.081058836 -0.035474722

In [71]:
x[x>-0.5 & x < 0.5]<-0
x

[1] -1.0098559 -1.4764955  0.0000000  0.5680658  0.8166302  0.7910656
  [7] -0.5080006  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000
 [13]  1.1319771  0.0000000  0.0000000 -0.5802814  0.0000000  0.7284466
 [19]  0.9782766 -0.8674249  0.0000000 -0.5763544 -0.5225471  0.9306117
 [25] -1.5642335  2.2167589  1.4688775  0.0000000 -1.5837994  1.4513758
 [31] -1.0498189  0.0000000  0.8187937  0.0000000 -1.7090992  0.0000000
 [37]  0.9828479 -1.2555709  0.0000000  1.4327972 -0.6438016  1.1594378
 [43]  0.9143597 -1.4658706 -1.4247272 -1.1041597 -2.6068161 -0.5026308
 [49] -1.3224971  1.0910874  1.2385747  0.0000000  0.0000000  0.0000000
 [55]  1.3369359  0.0000000 -1.1067720 -0.7618400 -1.3419360  0.0000000
 [61] -2.4094421 -1.1078239  1.3290769  0.0000000 -0.7767445  1.4229952
 [67]  0.0000000 -1.0760776  0.0000000  0.0000000 -1.4981912  0.0000000
 [73]  0.0000000 -1.2949269 -0.5509115  0.0000000 -0.5116923 -1.3947185
 [79]  1.4707667  0.0000000 -2.5126906 -0.7913264  0.7474043 -0.9852962
 [85] -1.2701929 -0.9284969  0.0000000  1.4098765  0.0000000  0.7665444
 [91]  2.5273391  1.6233023  1.4746506  0.0000000 -0.9488395 -1.4704197
 [97]  0.0000000  0.5111899  0.6149015 -0.5870411

In [61]:
x<- 1:10
x

[1]  1  2  3  4  5  6  7  8  9 10

In [60]:
x<- 15:8
x

[1] 15 14 13 12 11 10  9  8

In [42]:
seq(2,13,by=1.8)

[1]  2.0  3.8  5.6  7.4  9.2 11.0 12.8

In [43]:
seq(15,7,by=-2)

[1] 15 13 11  9  7

In [44]:
seq(2,13,length.out = 8) # 8 eşit parçaya bölecek

[1]  2.000000  3.571429  5.142857  6.714286  8.285714  9.857143 11.428571
[8] 13.000000

In [45]:
rep(1:3,times=3)

[1] 1 2 3 1 2 3 1 2 3

In [46]:
rep(1:3,length.out=8) # eleman sayısı 8 olana kadar çoğaltıcak

[1] 1 2 3 1 2 3 1 2

In [47]:
rep(1:3,each=3) # vektörün içine aldığı elemanları sırayla 3 defa çoğaltıyor.

[1] 1 1 1 2 2 2 3 3 3

In [48]:
x<-1:5

In [49]:
y<-2:6

In [50]:
x+y

[1]  3  5  7  9 11

In [51]:
x*y

[1]  2  6 12 20 30

In [53]:
sum(x)
mean(x)
var(x)
sd(x)

[1] 15

[1] 3

[1] 2.5

[1] 1.581139

In [56]:
y<-rnorm(100)   # "Mean Squared Error"
yhat<-rnorm(100)

In [58]:
mean((y-yhat)**2)

[1] 2.057261

In [73]:
m<-matrix(1:6,nrow=3)
m

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [76]:
m<-matrix(1:6,nrow=3,byrow = TRUE)
m

[,1] [,2]
[1,] 1    2   
[2,] 3    4   
[3,] 5    6

In [78]:
m<-matrix(1:12,nrow=3)
m

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [79]:
m[2,3]

[1] 8

In [80]:
m[2,]

[1]  2  5  8 11

In [81]:
m[,3]

[1] 7 8 9

In [82]:
m[,2:4]

[,1] [,2] [,3]
[1,] 4    7    10  
[2,] 5    8    11  
[3,] 6    9    12

In [83]:
m[2:3,3:4]

[,1] [,2]
[1,] 8    11  
[2,] 9    12

In [84]:
m[m[,2]>=5,4] # 2. ve 3. satırın 4. sütununu çekicek

[1] 11 12

In [86]:
gender<- ifelse(runif(10)>0.5,"male","female")
 # rastgele 10 sayı ürettik.sayılar 0.5' den büyükse male değilse female

In [87]:
gender

[1] "female" "female" "male"   "male"   "female" "female" "female" "female"
 [9] "female" "male"

In [89]:
gender_factor<-factor(gender)
gender_factor

[1] female female male   male   female female female female female male  
Levels: female male

In [91]:
grades<-sample(c("A","B","C","D","E"), size = 20,replace = TRUE)
grades

[1] "D" "B" "E" "A" "C" "B" "B" "E" "C" "A" "B" "B" "C" "B" "C" "B" "E" "C" "A"
[20] "A"

In [94]:
gender_factor<-factor(grades,ordered = TRUE)
gender_factor

[1] D B E A C B B E C A B B C B C B E C A A
Levels: A < B < C < D < E

In [95]:
mtcars

mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4   
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2   
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1   
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4   
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2   
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2   
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4   
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4   
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3   
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3   
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3   
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4   
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4   
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4   
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1   
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2   
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1   
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1   
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2   
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2   
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4   
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2   
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1   
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2   
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2   
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4   
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6   
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8   
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [96]:
tail(mtcars)

mpg  cyl disp  hp  drat wt    qsec vs am gear carb
Porsche 914-2  26.0 4   120.3  91 4.43 2.140 16.7 0  1  5    2   
Lotus Europa   30.4 4    95.1 113 3.77 1.513 16.9 1  1  5    2   
Ford Pantera L 15.8 8   351.0 264 4.22 3.170 14.5 0  1  5    4   
Ferrari Dino   19.7 6   145.0 175 3.62 2.770 15.5 0  1  5    6   
Maserati Bora  15.0 8   301.0 335 3.54 3.570 14.6 0  1  5    8   
Volvo 142E     21.4 4   121.0 109 4.11 2.780 18.6 1  1  4    2

In [97]:
str(mtcars)

'data.frame':	32 obs. of  11 variables:
 $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
 $ cyl : num  6 6 4 6 8 6 8 4 4 6 ...
 $ disp: num  160 160 108 258 360 ...
 $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...
 $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
 $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
 $ qsec: num  16.5 17 18.6 19.4 17 ...
 $ vs  : num  0 0 1 1 0 1 0 1 1 1 ...
 $ am  : num  1 1 1 0 0 0 0 0 0 0 ...
 $ gear: num  4 4 4 3 3 3 3 4 4 4 ...
 $ carb: num  4 4 1 1 2 1 4 2 2 4 ...


In [98]:
mtcars[1:5,2:4]

cyl disp hp 
Mazda RX4         6   160  110
Mazda RX4 Wag     6   160  110
Datsun 710        4   108   93
Hornet 4 Drive    6   258  110
Hornet Sportabout 8   360  175

In [99]:
mtcars["mpg"]

mpg 
Mazda RX4           21.0
Mazda RX4 Wag       21.0
Datsun 710          22.8
Hornet 4 Drive      21.4
Hornet Sportabout   18.7
Valiant             18.1
Duster 360          14.3
Merc 240D           24.4
Merc 230            22.8
Merc 280            19.2
Merc 280C           17.8
Merc 450SE          16.4
Merc 450SL          17.3
Merc 450SLC         15.2
Cadillac Fleetwood  10.4
Lincoln Continental 10.4
Chrysler Imperial   14.7
Fiat 128            32.4
Honda Civic         30.4
Toyota Corolla      33.9
Toyota Corona       21.5
Dodge Challenger    15.5
AMC Javelin         15.2
Camaro Z28          13.3
Pontiac Firebird    19.2
Fiat X1-9           27.3
Porsche 914-2       26.0
Lotus Europa        30.4
Ford Pantera L      15.8
Ferrari Dino        19.7
Maserati Bora       15.0
Volvo 142E          21.4

In [100]:
mtcars[c("mpg","cyl","hp")]

mpg  cyl hp 
Mazda RX4           21.0 6   110
Mazda RX4 Wag       21.0 6   110
Datsun 710          22.8 4    93
Hornet 4 Drive      21.4 6   110
Hornet Sportabout   18.7 8   175
Valiant             18.1 6   105
Duster 360          14.3 8   245
Merc 240D           24.4 4    62
Merc 230            22.8 4    95
Merc 280            19.2 6   123
Merc 280C           17.8 6   123
Merc 450SE          16.4 8   180
Merc 450SL          17.3 8   180
Merc 450SLC         15.2 8   180
Cadillac Fleetwood  10.4 8   205
Lincoln Continental 10.4 8   215
Chrysler Imperial   14.7 8   230
Fiat 128            32.4 4    66
Honda Civic         30.4 4    52
Toyota Corolla      33.9 4    65
Toyota Corona       21.5 4    97
Dodge Challenger    15.5 8   150
AMC Javelin         15.2 8   150
Camaro Z28          13.3 8   245
Pontiac Firebird    19.2 8   175
Fiat X1-9           27.3 4    66
Porsche 914-2       26.0 4    91
Lotus Europa        30.4 4   113
Ford Pantera L      15.8 8   264
Ferrari Dino        19.7 6   175
Maserati Bora       15.0 8   335
Volvo 142E          21.4 4   109

In [101]:
mtcars$wt

[1] 2.620 2.875 2.320 3.215 3.440 3.460 3.570 3.190 3.150 3.440 3.440 4.070
[13] 3.730 3.780 5.250 5.424 5.345 2.200 1.615 1.835 2.465 3.520 3.435 3.840
[25] 3.845 1.935 2.140 1.513 3.170 2.770 3.570 2.780